-- Make ticket_number have a proper default so it's not required on insert
-- It's already generated by the trigger, but we need the column to not require a value

ALTER TABLE public.support_tickets 
ALTER COLUMN ticket_number SET DEFAULT '';

-- The trigger will override this with the proper value