// Mock demo data for product tour
// Used when ?demo=active to show a populated dashboard experience

export const DEMO_BRAND = {
  id: "demo-brand-id",
  slug: "acme-brand",
  name: "Acme Brand Co.",
  logo_url: null,
  description: "A demo brand showcasing the Virality platform",
};

export const DEMO_CAMPAIGNS = [
  {
    id: "demo-campaign-1",
    title: "Summer Product Launch",
    description: "Promote our new summer collection with engaging content",
    budget: 5000,
    spent: 2340,
    status: "active",
    cpm_rate: 8.5,
    submissions_count: 45,
    approved_count: 32,
    total_views: 275000,
    created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-campaign-2",
    title: "Brand Awareness Q4",
    description: "Build brand recognition heading into the holiday season",
    budget: 10000,
    spent: 0,
    status: "draft",
    cpm_rate: 10,
    submissions_count: 0,
    approved_count: 0,
    total_views: 0,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-campaign-3",
    title: "Influencer Partnership",
    description: "Collaborate with micro-influencers for authentic content",
    budget: 3500,
    spent: 3500,
    status: "completed",
    cpm_rate: 7.5,
    submissions_count: 28,
    approved_count: 28,
    total_views: 467000,
    created_at: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const DEMO_BOOSTS = [
  {
    id: "demo-boost-1",
    title: "Viral Challenge Boost",
    description: "Boost engagement with our trending hashtag challenge",
    budget: 2000,
    spent: 850,
    status: "active",
    reward_per_1k_views: 2.5,
    participants: 156,
    total_views: 340000,
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-boost-2",
    title: "Product Review Push",
    description: "Incentivize authentic product reviews from creators",
    budget: 1500,
    spent: 0,
    status: "draft",
    reward_per_1k_views: 3,
    participants: 0,
    total_views: 0,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const DEMO_CREATORS = [
  {
    id: "demo-creator-1",
    name: "Alex Johnson",
    username: "alexcreates",
    avatar_url: "/demo-avatars/avatar-1.jpg",
    followers: 150000,
    niche: "Tech & Gadgets",
    engagement_rate: 4.2,
    avg_views: 45000,
    completed_campaigns: 12,
    rating: 4.8,
  },
  {
    id: "demo-creator-2",
    name: "Sarah Miller",
    username: "sarahstyle",
    avatar_url: "/demo-avatars/avatar-8.jpg",
    followers: 280000,
    niche: "Fashion & Lifestyle",
    engagement_rate: 5.1,
    avg_views: 82000,
    completed_campaigns: 8,
    rating: 4.9,
  },
  {
    id: "demo-creator-3",
    name: "Marcus Chen",
    username: "marcusfitness",
    avatar_url: "/demo-avatars/avatar-38.jpg",
    followers: 95000,
    niche: "Fitness & Health",
    engagement_rate: 6.3,
    avg_views: 32000,
    completed_campaigns: 15,
    rating: 4.7,
  },
  {
    id: "demo-creator-4",
    name: "Emma Davis",
    username: "emmaeats",
    avatar_url: "/demo-avatars/avatar-44.jpg",
    followers: 420000,
    niche: "Food & Cooking",
    engagement_rate: 4.8,
    avg_views: 125000,
    completed_campaigns: 22,
    rating: 5.0,
  },
];

export const DEMO_CONTRACTS = [
  {
    id: "demo-contract-1",
    title: "Monthly Content Partnership",
    creator_name: "Alex Johnson",
    creator_avatar: "/demo-avatars/avatar-1.jpg",
    boost_title: "Summer Product Launch",
    status: "signed",
    monthly_rate: 500,
    videos_per_month: 3,
    start_date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    signed_at: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    terms: "Creator will produce 3 videos per month featuring brand products.",
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-contract-2",
    title: "Brand Ambassador Agreement",
    creator_name: "Sarah Miller",
    creator_avatar: "/demo-avatars/avatar-8.jpg",
    boost_title: "Summer Product Launch",
    status: "sent",
    monthly_rate: 750,
    videos_per_month: 2,
    start_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    terms: "Exclusive partnership for 3 months with option to renew.",
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-contract-3",
    title: "Product Review Series",
    creator_name: "Marcus Chen",
    creator_avatar: "/demo-avatars/avatar-38.jpg",
    boost_title: null,
    status: "draft",
    monthly_rate: 400,
    videos_per_month: 4,
    start_date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    terms: "Weekly product reviews with honest feedback.",
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const DEMO_WALLET = {
  balance: 12500,
  virality_balance: 10000,
  withdraw_balance: 0,
  pending_balance: 2500,
  currency: "USD",
};

export const DEMO_TRANSACTIONS = [
  {
    id: "demo-tx-1",
    type: "topup",
    amount: 5000,
    status: "completed",
    description: "Card deposit",
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-tx-2",
    type: "allocation",
    amount: -2000,
    status: "completed",
    description: "Funded: Summer Product Launch",
    created_at: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-tx-3",
    type: "crypto_deposit",
    amount: 7500,
    status: "completed",
    description: "USDC deposit (Solana)",
    created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-tx-4",
    type: "allocation",
    amount: -3000,
    status: "completed",
    description: "Funded: Influencer Partnership",
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-tx-5",
    type: "topup",
    amount: 2500,
    status: "pending",
    description: "Wire transfer (processing)",
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const DEMO_LEADERBOARD = [
  { rank: 1, creator: DEMO_CREATORS[3], total_views: 2450000, earnings: 4900 },
  { rank: 2, creator: DEMO_CREATORS[1], total_views: 1820000, earnings: 3640 },
  { rank: 3, creator: DEMO_CREATORS[0], total_views: 980000, earnings: 1960 },
  { rank: 4, creator: DEMO_CREATORS[2], total_views: 650000, earnings: 1300 },
];

export const DEMO_BLUEPRINTS = [
  {
    id: "demo-blueprint-1",
    title: "Summer Vibes Content Guide",
    status: "assigned",
    content: "Create engaging summer-themed content showcasing our products in outdoor settings.",
    platforms: ["tiktok", "instagram"],
    hooks: ["Start with an eye-catching outdoor scene", "Use trending summer sounds"],
    talking_points: ["Product benefits", "Summer use cases", "Limited time offer"],
    hashtags: ["#SummerVibes", "#AcmeBrand", "#SummerStyle"],
    created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    created_by: "demo-user",
    creator: null,
  },
  {
    id: "demo-blueprint-2",
    title: "Product Unboxing Template",
    status: "draft",
    content: "Standard unboxing format for new product launches.",
    platforms: ["youtube", "tiktok"],
    hooks: ["Build anticipation with close-up shots", "Reveal moment with excitement"],
    talking_points: ["Packaging quality", "First impressions", "Key features"],
    hashtags: ["#Unboxing", "#NewProduct", "#FirstLook"],
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    created_by: "demo-user",
    creator: null,
  },
  {
    id: "demo-blueprint-3",
    title: "Tutorial Style Guide",
    status: "assigned",
    content: "Educational content showing how to use our products effectively.",
    platforms: ["youtube", "instagram", "tiktok"],
    hooks: ["Problem statement hook", "Before/after transformation"],
    talking_points: ["Step-by-step instructions", "Pro tips", "Common mistakes to avoid"],
    hashtags: ["#HowTo", "#Tutorial", "#Tips"],
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    created_by: "demo-user",
    creator: null,
  },
];
