// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Check if Web Locks API is available (not in all browsers/contexts)
const supportsLocking = typeof navigator !== 'undefined' && 'locks' in navigator;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Use Web Locks API to prevent concurrent token refreshes across tabs/components
    // This fixes the race condition that causes "refresh_token_already_used" errors
    // Falls back to no-op if Web Locks API is not available
    lock: supportsLocking ? 'navigator' : 'no-op',
    detectSessionInUrl: true,
    flowType: 'pkce',
  }
});